name: self-hosted runner

on:
    push:
        branches: 
            - feature

jobs:
    local_runner:
        runs-on: self-hosted
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: validate functioning
              run: |
                aws configure
                ls
